version:  '3'
services:
  datascience-notebook:
      image:    jupyter/datascience-notebook
      volumes:
        - workspace:/home/jovyan/work
      container_name: jupyter_notebook
      restart: unless-stopped
      networks:
        - reverseproxy-nw
volumes:
  workspace:
networks:
  reverseproxy-nw:
    external: true
