version: "2.1"
services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload-ng
    environment:
      - PUID=996
      - PGID=996
      - TZ=Etc/UTC
    volumes:
      - config:/config
      - downloads:/downloads
    ports:
      - 8001:8000
#      - 9666:9666 #optional
    restart: unless-stopped


volumes:
  config:
    driver: risteon/buttervolume
    driver_opts:
      copyonwrite: "true"
  downloads:
    driver: risteon/buttervolume
    driver_opts:
      copyonwrite: "false"
