homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
frontend:
  port: 8080
  host: 0.0.0.0
  url: https://zigbee2mqtt.wachtel.weg
serial:
  port: /dev/ttyUSB0
advanced:
  # Optional: Logging level, options: debug, info, warn, error (default: info)
  log_level: warn
