version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: reverse-nginx-proxy
    restart: always
    environment:
      DEFAULT_HOST: default.vhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - config:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    #image: stefanscherer/whoami:linux-arm64-2.0.1
    image: whoami2:latest
    restart: always
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_PORT=8000

  acme:
    image: nginxproxy/acme-companion
    restart: always
    container_name: nginx-proxy-acme
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=c.rist@posteo.de
      - NGINX_DOCKER_GEN_CONTAINER=reverse-nginx-proxy
      - NGINX_PROXY_CONTAINER=reverse-nginx-proxy
    depends_on:
      - reverse-nginx-proxy

volumes:
  vhost:
  html:
  certs:
  acme:
  config:
