version: '3'
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - config:/config
    ports:
      - 8123:8123 #optional
    #devices:
    #  - /path/to/device:/path/to/device #optional
    restart: unless-stopped
    networks:
      - reverseproxy-nw
      - homeassistant-nw

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - homeassistant-nw


  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - zigbee2mqtt_data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/ttyUSB0
    networks:
      - reverseproxy-nw
      - homeassistant-nw
    group_add:
      - dialout
    user: 1000:1000
    depends_on:
      - "mosquitto"

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    restart: unless-stopped
    volumes:
      - appdaemon_conf:/conf
      - appdaemon_logs:/logs
    ports:
      # Frontend port
      - 5050:5050
    environment:
      - TZ=Europe/Berlin
      - HA_URL="http://homeassistant:8123"
    networks:
      - reverseproxy-nw
      - homeassistant-nw
    depends_on:
      - "homeassistant"

volumes:
  config:
    driver: risteon/buttervolume
    driver_opts:
      copyonwrite: "false"
  zigbee2mqtt_data:
    driver: risteon/buttervolume
    driver_opts:
      copyonwrite: "true"
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  appdaemon_conf:
    driver: risteon/buttervolume
    driver_opts:
      copyonwrite: "true"
  appdaemon_logs:
    driver: risteon/buttervolume
    driver_opts:
      copyonwrite: "true"
networks:
  homeassistant-nw:
  reverseproxy-nw:
    external: true
