services:
  db:
    image: postgres:14-alpine
    restart: always
    networks:
      - nextcloud-nw
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  app:
    image: nextcloud:28.0-fpm-alpine
    restart: always
    networks:
      - nextcloud-nw
    links:
      - db
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

  web:
    image: nginx:stable-alpine
    restart: always
    networks:
      - proxy
      - nextcloud-nw
    links:
      - app
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.nextcloud-secure-headers.headers.hostsProxyHeaders=X-Forwarded-Host"
      - "traefik.http.middlewares.nextcloud-secure-headers.headers.referrerPolicy=same-origin"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`storage.risteon.xyz`)"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.middlewares[0]=nextcloud-secure-headers"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`storage.risteon.xyz`)"
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  nextcloud-nw:
  proxy:
    external: true

volumes:
  db:
    driver: anybox/buttervolume
    driver_opts:
      copyonwrite: "false"
  nextcloud:
    driver: anybox/buttervolume
    driver_opts:
      copyonwrite: "true"

secrets:
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: ./nextcloud_admin_user.txt # put admin username to this file
  postgres_db:
    file: ./postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: ./postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: ./postgres_user.txt # put postgresql username to this file
