version: "3.2"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:development-version-v2.0.6.106-2.0.6.106_canary_2023-05-03
    container_name: duplicati-aws
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
#      - CLI_ARGS= #optional
    volumes:
      - config:/config
      - scripts:/scripts
      - /mnt/data/duplicati:/backup
      - type: bind
        source: /btrbk-duplicati/snapshots
        target: /source
        read_only: true
      - /btrbk-duplicati/pipe:/pipe
    ports:
      - 8201:8200
    restart: unless-stopped
    networks:
      - reverseproxy-nw

volumes:
  config:
    driver: risteon/buttervolume
    driver_opts:
      copyonwrite: "true"
  scripts:
    driver: risteon/buttervolume
    driver_opts:
      copyonwrite: "true"
networks:
  reverseproxy-nw:
    external: true
