#!/bin/bash
# Create and delete read-only snapshots of btrfs subvolumes under a certain dir. Only this dir is allowed.
set -eu
src_dir="/var/lib/buttervolume/volumes"
snapshot_dir="/btrbk-duplicati/snapshots"

create_snapshot () {
  # get absolute path
  subvol=$(readlink -f "${src_dir}/${1}")
  # only allow folders under src_dir
  if [[ "${subvol}/" != ${src_dir}/* ]]; then
    exit 1
  fi
  
  btrfs subvolume snapshot -r "${subvol}" "${snapshot_dir}"
}

delete_snapshot () {
  # get absolute path
  subvol=$(readlink -f "${snapshot_dir}/${1}")
  # only allow folders under src_dir
  if [[ "${subvol}/" != ${snapshot_dir}/* ]]; then
    exit 1
  fi
  
  btrfs subvolume delete "${subvol}"
}

case "$1" in
"create")
    create_snapshot "${2}"
    ;;
"delete")
    delete_snapshot "${2}"
    ;;
*)
    echo "Invalid command ${1}" 1>&2
    exit 1
    ;;
esac

