services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    # use docker volume as data dir
    volumes:
      - "data:/etc/linkding/data"
    env_file:
      - stack.env
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.linkding-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.linkding.entrypoints=http"
      - "traefik.http.routers.linkding.rule=Host(`linkding.risteon.xyz`)"
      - "traefik.http.routers.linkding.middlewares=linkding-https-redirect"
      - "traefik.http.routers.linkding-secure.entrypoints=https"
      - "traefik.http.routers.linkding-secure.rule=Host(`linkding.risteon.xyz`)"
      - "traefik.http.routers.linkding-secure.tls=true"
      - "traefik.http.routers.linkding-secure.service=linkding"
      - "traefik.http.services.linkding.loadbalancer.server.port=9090"
      - "traefik.docker.network=proxy"

volumes:
  data:
    driver: anybox/buttervolume
    driver_opts:
      copyonwrite: "true"

networks:
  proxy:
    external: true
