services:
  ghostfolio:
    image: ghostfolio/ghostfolio:2.76.0
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?connect_timeout=300&sslmode=prefer
      NODE_ENV: production
      REDIS_HOST: redis
    networks:
      - proxy
      - default
    #   ports:
    #     - 3333:3333
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.ghostfolio-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.ghostfolio-local.ipwhitelist.sourcerange=127.0.0.1/32, 100.10.10.0/24"
      - "traefik.http.routers.ghostfolio.entrypoints=http"
      - "traefik.http.routers.ghostfolio.rule=Host(`ghostfolio.local.risteon.xyz`)"
      - "traefik.http.routers.ghostfolio.middlewares=ghostfolio-https-redirect"
      - "traefik.http.routers.ghostfolio-secure.entrypoints=https"
      - "traefik.http.routers.ghostfolio-secure.rule=Host(`ghostfolio.local.risteon.xyz`)"
      - "traefik.http.routers.ghostfolio-secure.tls=true"
      - "traefik.http.routers.ghostfolio-secure.service=ghostfolio"
      - "traefik.http.routers.ghostfolio-secure.middlewares=ghostfolio-local"
      - "traefik.http.services.ghostfolio.loadbalancer.server.port=3333"
      - "traefik.docker.network=proxy"
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}'
        ]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    env_file:
      - .env
    healthcheck:
      test: [ 'CMD-SHELL', 'redis-cli ping | grep PONG' ]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  default:
  proxy:
    external: true

volumes:
  postgres:
    driver: anybox/buttervolume
    driver_opts:
      copyonwrite: "true"
