version: '3.9'
services:
  ghostfolio:
    image: ghostfolio/ghostfolio:2.0.0
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?connect_timeout=300&sslmode=prefer
      NODE_ENV: production
      REDIS_HOST: redis
    networks:
      - reverseproxy-nw
      - default
#   ports:
#     - 3333:3333
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  default:
  reverseproxy-nw:
    external: true

volumes:
  postgres:
    driver: risteon/buttervolume
    driver_opts:
      copyonwrite: "false"

