name: 'ripping-machine'

services:
  ripping-machine:
    image: automaticrippingmachine/automatic-ripping-machine
    cpuset: "0,1,2,3,4,5,6,7,8,9,10"
    environment:
      - ARM_UID=995
      - ARM_GID=985
      # - ARM_UID=0
      # - ARM_GID=0
      # - TZ=Europe/London
    volumes:
      - apps:/home/arm
      - logs:/home/arm/logs
      - config:/etc/arm/config
      - type: bind
        source: /mnt/cache/ripping-machine_media
        target: /home/arm/media
        read_only: false
      - type: bind
        source: /mnt/cache/ripping-machine_music
        target: /home/arm/music
        read_only: false
      # ports:
      #  - 8080:8080
    devices:
      - "/dev/sr0:/dev/sr0"
    restart: unless-stopped
    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.ripping-machine-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.ripping-machine-local.ipwhitelist.sourcerange=127.0.0.1/32, 100.10.10.0/24"
      - "traefik.http.routers.ripping-machine.entrypoints=http"
      - "traefik.http.routers.ripping-machine.rule=Host(`ripping-machine.local.risteon.xyz`)"
      - "traefik.http.routers.ripping-machine.middlewares=ripping-machine-https-redirect"
      - "traefik.http.routers.ripping-machine-secure.entrypoints=https"
      - "traefik.http.routers.ripping-machine-secure.rule=Host(`ripping-machine.local.risteon.xyz`)"
      - "traefik.http.routers.ripping-machine-secure.tls=true"
      - "traefik.http.routers.ripping-machine-secure.service=ripping-machine"
      - "traefik.http.routers.ripping-machine-secure.middlewares=ripping-machine-local"
      - "traefik.http.services.ripping-machine.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

volumes:
  apps:
    driver: anybox/buttervolume
    driver_opts:
      copyonwrite: "true"
  logs:
    driver: anybox/buttervolume
    driver_opts:
      copyonwrite: "true"
  config:
    driver: anybox/buttervolume
    driver_opts:
      copyonwrite: "true"

networks:
  proxy:
    external: true
