# docker-compose.yml 
version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/data
    ports:
      - 8000:8000
      - 9443:9443
    networks:
      - reverseproxy-nw
volumes:
  data:
networks:
  reverseproxy-nw:
    external: true
