services:
  ddclient:
    image: ddclient
    build: ./image
    container_name: ddclient
    volumes:
      - config:/config
      - cmd:/cmd
    restart: unless-stopped

volumes:
  config:
    driver: risteon/buttervolume
    driver_opts:
      copyonwrite: "true"
  cmd:
    driver: risteon/buttervolume
    driver_opts:
      copyonwrite: "true"
