version: "2.1"
services:
  ddclient:
    image: linuxserver/ddclient:arm32v7-version-v3.9.1
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - config:/config
    restart: unless-stopped

volumes:
  config:
