version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: "npm"
    restart: unless-stopped
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - nginx-proxy-manager
      - reverseproxy-nw
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nginx-proxy-manager
volumes:
  data:
  letsencrypt:
  db_data:
networks:
  nginx-proxy-manager:
  reverseproxy-nw:
    external: true
