name: 'duplicati'

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:development-version-v2.0.7.102-2.0.7.102_canary_2024-04-03
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    #      - CLI_ARGS= #optional
    volumes:
      - config:/config
      - scripts:/scripts
      - /mnt/data/duplicati:/backup
      - type: bind
        source: /btrfs-duplicati/snapshots
        target: /source
        read_only: true
      - /btrfs-duplicati/pipe:/pipe
    # ports:
    #  - 8200:8200
    restart: unless-stopped
    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.duplicati-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.duplicati-local.ipwhitelist.sourcerange=127.0.0.1/32, 100.10.10.0/24"
      - "traefik.http.routers.duplicati.entrypoints=http"
      - "traefik.http.routers.duplicati.rule=Host(`duplicati.local.risteon.xyz`)"
      - "traefik.http.routers.duplicati.middlewares=duplicati-https-redirect"
      - "traefik.http.routers.duplicati-secure.entrypoints=https"
      - "traefik.http.routers.duplicati-secure.rule=Host(`duplicati.local.risteon.xyz`)"
      - "traefik.http.routers.duplicati-secure.tls=true"
      - "traefik.http.routers.duplicati-secure.service=duplicati"
      - "traefik.http.routers.duplicati-secure.middlewares=duplicati-local"
      - "traefik.http.services.duplicati.loadbalancer.server.port=8200"
      - "traefik.docker.network=proxy"

volumes:
  config:
    driver: anybox/buttervolume
    driver_opts:
      copyonwrite: "true"
  scripts:
    driver: anybox/buttervolume
    driver_opts:
      copyonwrite: "true"

networks:
  proxy:
    external: true
